### ISSUE TITLE
Starter kit with enabled JSX support

### ISSUE THREAD

**Issue by PTihomir** [yummies/starter-kit#3]
Hi! I tried to enable reBEM JSX support for my project, but failed miserably. So I took the starter kit, expecting that it will have it configured, but no. So I tried to enable it for starter kit, hoped that I will succeed and by that I will figure out the what was the problem initially on my project, but nope, I was not lucky enough...

So I would really appreciate a version of the starter kit with enabled jsx support, or some help how to configure webpack.

Currently module build fails because of the unexpected HTML syntax.

**Comment by deepsweet** [comment]
I'll make a special branch with reBEM JSX soon.

**Comment by PTihomir** [comment]
Thanks :)

**Comment by deepsweet** [comment]
https://github.com/rebem/starter-kit/commit/45d743ac953b81f51a1f461730eba3c98dc09ed4

most likely you just forgot about "babel-preset-react" dependency. if you are using rebem-layers, then you have to set `importFactory: false` in your layers config, [see docs](https://github.com/rebem/layers-loader#importfactory).

feel free to ask for further help :)

**Comment by PTihomir** [comment]
Thanks. Yep, I missed to install "babel-preser-react" but after installing it it started to work. Thanks for the JSX version!
